extends SceneTree
## Pure construction contracts; does not enable the class or simulate paid casts.

const A := Vector2(100, 100)
const B := Vector2(400, 100)
const C := Vector2(100, 400)
var checks := 0
var failures := 0

func _initialize() -> void:
	_run.call_deferred()

func _run() -> void:
	_geometry()
	_grammar()
	_construction()
	_mobile()
	print("Geometer construction: %d checks, %d failures" % [checks, failures])
	quit(1 if failures else 0)

func _nav(obstacles: Array[Rect2] = []) -> ArenaNavigation:
	var navigation := ArenaNavigation.new()
	navigation.configure(Rect2(0, 0, 1000, 800), obstacles, 18.0)
	return navigation

func _check(condition: bool, label: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		push_error(label)

func _geometry() -> void:
	var nav := _nav()
	var triangle := PackedVector2Array([A, B, C])
	_check(GeometerGeometry.validate(triangle, nav)["ok"], "valid triangle")
	_check(GeometerGeometry.validate(PackedVector2Array([C, B, A]), nav)["ok"], "winding does not change validity")
	_check(GeometerGeometry.triangle_area(triangle) == 45000.0, "arena-space area")
	_check(not GeometerGeometry.validate(PackedVector2Array(), nav)["ok"], "empty geometry rejected")
	_check(not GeometerGeometry.validate(PackedVector2Array([A, B, C, Vector2(400, 400)]), nav)["ok"], "fourth vertex rejected")
	_check(not GeometerGeometry.validate(PackedVector2Array([Vector2(NAN, 100)]), nav)["ok"], "nonfinite point rejected")
	_check(not GeometerGeometry.validate(PackedVector2Array([Vector2(-1, 100)]), nav)["ok"], "outside arena rejected")
	_check(GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(24, 0)]), nav)["ok"], "24-unit separation accepted")
	_check(not GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(23.9, 0)]), nav)["ok"], "short separation rejected")
	_check(GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(600, 0)]), nav)["ok"], "600-unit edge accepted")
	_check(not GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(600.1, 0)]), nav)["ok"], "overlong edge rejected")
	_check(not GeometerGeometry.validate(PackedVector2Array([A, B, Vector2(200, 100)]), nav)["ok"], "collinear vertices rejected")
	_check(GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(32, 0), A + Vector2(0, 16)]), nav)["ok"] == false, "separation checked independently of area")
	_check(GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(64, 0), A + Vector2(32, 8)]), nav)["ok"], "minimum area 256 accepted")
	_check(not GeometerGeometry.validate(PackedVector2Array([A, A + Vector2(64, 0), A + Vector2(32, 7.9)]), nav)["ok"], "area below 256 rejected")
	var enclosed := _nav([Rect2(180, 180, 20, 20)])
	_check(enclosed.is_segment_clear(A, B, 0.0) and enclosed.is_segment_clear(B, C, 0.0) and enclosed.is_segment_clear(C, A, 0.0), "enclosed obstacle leaves edges clear")
	_check(not GeometerGeometry.validate(triangle, enclosed)["ok"], "enclosed obstacle invalidates interior")
	_check(GeometerGeometry.validate(triangle, _nav([Rect2(350, 350, 20, 20)]))["ok"], "obstacle in AABB but outside triangle allowed")
	_check(nav.add_temporary_segment(10, Vector2(180, 180), Vector2(210, 180), 6.0, []), "temporary segment fixture installed")
	_check(not GeometerGeometry.validate(triangle, nav)["ok"], "enclosed temporary barrier rejected")
	nav.remove_temporary_segment(10)
	_check(GeometerGeometry.validate(triangle, nav)["ok"], "removing barrier restores validity")
	_check(GeometerGeometry.triangle_contains(triangle, Vector2(200, 200)), "inside hit-test")
	_check(GeometerGeometry.triangle_contains(triangle, Vector2(250, 95), 5.0), "circle touching edge included")
	_check(not GeometerGeometry.triangle_contains(triangle, Vector2(250, 94.9), 5.0), "outside circle excluded")
	_check(not GeometerGeometry.triangle_contains(PackedVector2Array([A, B, Vector2(NAN, 400)]), A), "hit-test rejects nonfinite geometry")
	_check(not GeometerGeometry.triangle_contains(triangle, A, -1.0), "negative radius rejected")
	var rank_counts := {1: 0, 3: 0, 5: 0}
	for first: StringName in GeometerGeometry.ELEMENTS:
		for second: StringName in GeometerGeometry.ELEMENTS:
			for third: StringName in GeometerGeometry.ELEMENTS:
				var tokens: Array[StringName] = [first, second, third]
				var expected := 1 if first == second and second == third else (5 if first != second and first != third and second != third else 3)
				var rank := GeometerGeometry.triangle_rank(tokens)
				_check(rank == expected, "recipe %s/%s/%s has correct gate" % [first, second, third])
				rank_counts[rank] += 1
	_check(rank_counts == {1: 3, 3: 18, 5: 6}, "all 27 recipes: three pure, 18 mixed, six tricolor")
	_check(GeometerGeometry.triangle_rank([&"fire", &"ice", &"invalid"]) == 0, "invalid token rejected")

func _grammar() -> void:
	var grammar := GeometerGrammarState.new()
	_check(not grammar.select_element(&"water") and grammar.selected_element == &"fire", "invalid selection preserves element")
	var context := {"nested": {"rank": 1}}
	var first := grammar.reserve(A, 0, 0, context)
	context["nested"]["rank"] = 5
	grammar.select_element(&"ice")
	var second := grammar.reserve(B, 11, 0)
	_check(grammar.resolve(second, true, B).is_empty(), "later impact waits for first")
	_check(grammar.resolve(second, true, C).is_empty(), "duplicate resolved impact ignored")
	var ready := grammar.resolve(first, true, A)
	_check(ready.size() == 2 and ready[0]["element"] == &"fire" and ready[1]["element"] == &"ice", "command order and frozen elements preserved")
	_check(ready[0]["context"]["nested"]["rank"] == 1 and ready[1]["actor_id"] == 11 and ready[1]["point"] == B, "captured context and target intent isolated")
	_check(grammar.resolve(first, true, C).is_empty(), "delivered impact cannot replay")
	var old := grammar.reserve(A, 0, 0)
	grammar.clear()
	var fresh := grammar.reserve(B, 0, 0)
	_check(fresh > old and grammar.resolve(old, true, A).is_empty() and grammar.pending_count() == 1, "clear invalidates stale tickets without reusing IDs")
	grammar.clear()
	first = grammar.reserve(A, 0, 0, {}, 1.0)
	second = grammar.reserve(B, 0, 0, {}, 2.0)
	grammar.resolve(second, true, B)
	_check(grammar.advance(0.0).is_empty() and grammar.advance(-1.0).is_empty() and grammar.advance(NAN).is_empty(), "invalid delta does not advance queue")
	ready = grammar.advance(1.0)
	_check(ready.size() == 2 and not ready[0]["success"] and ready[1]["success"], "timeout releases later successful impact in order")
	_check(grammar.resolve(first, true, A).is_empty(), "timed-out impact cannot replay")
	_check(grammar.reserve(A, 0, 3) == 0 and grammar.reserve(A, -1, 0) == 0 and grammar.reserve(A, 0, 0, {}, INF) == 0, "capacity, target and timeout validated")
	grammar.reserve(A, 0, 1)
	grammar.reserve(B, 0, 1)
	_check(grammar.reserve(C, 0, 1) == 0, "confirmed plus pending capacity bounded")
	var snapshot := grammar.pending_snapshot()
	snapshot[0]["point"] = C
	_check(grammar.pending_snapshot()[0]["point"] == A, "preview snapshot cannot mutate queue")

func _construction() -> void:
	var nav := _nav()
	var alive: Dictionary[int, Vector2] = {}
	var state := GeometerConstructionState.new()
	_check(state.reserve_shot(A, 0, false, 0, nav, NAN) == 0 and state.grammar.pending_count() == 0, "invalid duration rejected before reservation")
	_check(state.consume_collapse().is_empty(), "empty construction cannot collapse")
	var first := state.reserve_shot(A, 0, false, 0, nav)
	state.grammar.select_element(&"ice")
	var second := state.reserve_shot(B, 0, false, 0, nav)
	_check(state.resolve_shot(second, true, B, alive, nav).is_empty() and state.vertices.is_empty(), "construction waits for ordered delivery")
	var results := state.resolve_shot(first, true, A, alive, nav)
	_check(results.size() == 2 and state.elements() == [&"fire", &"ice"] and state.shape == GeometerConstructionState.Shape.WALL, "two ordered impacts form correct wall")
	var identity := state.construction_id
	state.advance(1.0, alive, nav)
	_check(state.figure_remaining == 5.0, "wall clock advances")
	state.grammar.select_element(&"lightning")
	_check(state.reserve_shot(C, 0, false, 5, nav) == 0, "trace cannot silently fire third vertex")
	_check(state.reserve_shot(C, 0, true, 3, nav) == 0 and state.positions() == PackedVector2Array([A, B]), "locked tricolor preview preserves wall")
	var third := state.reserve_shot(C, 0, true, 5, nav)
	results = state.resolve_shot(third, true, C, alive, nav)
	_check(results.size() == 1 and results[0]["formation"] and state.shape == GeometerConstructionState.Shape.TRIANGLE, "explicit triangulation closes once")
	_check(state.figure_remaining == 5.0 and state.construction_id == identity, "wall to triangle preserves lifetime and identity")
	_check(state.resolve_shot(third, true, C, alive, nav).is_empty() and state.reserve_shot(Vector2(400, 400), 0, false, 5, nav) == 0, "no replay or fourth trace")
	var before := state.positions()
	_check(not state.edit(B, 0, false, 5, nav)["ok"] and state.positions() == before and state.figure_remaining == 5.0, "invalid edit is atomic")
	state.grammar.select_element(&"fire")
	var edited := state.edit(Vector2(100, 450), 0, false, 5, nav)
	_check(edited["ok"] and not edited["formation"] and state.elements() == [&"fire", &"ice", &"lightning"], "translation retains latest element and does not resolve C")
	_check(state.vertices[0].remaining == 7.0 and state.vertices[2].remaining == 8.0 and state.figure_remaining == 5.0, "edit refreshes only replaced vertex")
	edited = state.edit(Vector2(430, 430), 0, true, 5, nav)
	_check(edited["ok"] and state.elements() == [&"ice", &"lightning", &"fire"] and state.construction_id == identity and not edited["formation"], "rewrite rotates FIFO and preserves construction")
	var collapsed := state.consume_collapse()
	_check(collapsed["construction_id"] == identity and collapsed["remaining"] == 5.0 and state.shape == GeometerConstructionState.Shape.EMPTY, "collapse captures then consumes active figure")
	_check(state.consume_collapse().is_empty(), "collapse cannot repeat")
	state.add_vertex(&"fire", A, 0, 0, nav)
	_check(state.construction_id > identity and state.consume_collapse().is_empty(), "new ID and lone anchor cannot collapse")
	state.add_vertex(&"fire", B, 0, 0, nav)
	_check(state.shape == GeometerConstructionState.Shape.PREPARATION and not state.has_active_figure() and state.consume_collapse().is_empty(), "two identical vertices are inert preparation")
	var closed := state.add_vertex(&"fire", C, 0, 1, nav)
	_check(closed["ok"] and closed["formation"] and state.figure_remaining == 6.0, "pure triangle unlocks at rank one")
	state.advance(6.0, alive, nav)
	_check(state.shape == GeometerConstructionState.Shape.EMPTY, "figure expiry clears whole construction")
	state.add_vertex(&"fire", A, 0, 0, nav, 1.0)
	state.add_vertex(&"ice", B, 0, 0, nav)
	state.advance(1.0, alive, nav)
	_check(state.vertices.is_empty(), "any vertex expiry clears whole construction")
	first = state.reserve_shot(A, 0, false, 0, nav)
	state.clear()
	_check(state.resolve_shot(first, true, A, alive, nav).is_empty(), "construction clear rejects in-flight stale impact")
	first = state.reserve_shot(A, 0, false, 0, nav)
	_check(not state.edit(C, 0, false, 5, nav)["ok"], "pending shot cannot be edited")
	state.grammar.select_element(&"ice")
	second = state.reserve_shot(B, 0, false, 0, nav)
	state.resolve_shot(second, true, B, alive, nav)
	results = state.resolve_shot(first, false, A, alive, nav)
	_check(results.size() == 2 and not results[0]["ok"] and results[1]["ok"] and state.elements() == [&"ice"], "failed first shot does not donate its element to later impact")
	state.clear()
	state.add_vertex(&"fire", A, 0, 0, nav)
	state.add_vertex(&"fire", B, 0, 0, nav)
	state.add_vertex(&"fire", C, 0, 1, nav)
	state.grammar.select_element(&"ice")
	_check(not state.edit(Vector2(430, 430), 0, true, 1, nav)["ok"] and state.elements() == [&"fire", &"fire", &"fire"], "rewrite cannot bypass mixed recipe rank")
	state.clear()
	state.add_vertex(&"fire", A, 0, 0, nav)
	state.add_vertex(&"ice", B, 0, 0, nav)
	third = state.reserve_shot(C, 0, true, 3, nav)
	results = state.resolve_shot(third, true, Vector2(250, 100), alive, nav)
	_check(not results[0]["ok"] and state.shape == GeometerConstructionState.Shape.WALL and state.positions() == PackedVector2Array([A, B]), "invalid third impact preserves prior wall")
	state.clear()
	first = state.reserve_shot(A, 0, false, 0, nav)
	second = state.reserve_shot(B, 0, false, 0, nav, 1.0, 6.0, &"ice")
	state.resolve_shot(second, true, B, alive, nav)
	results = state.advance(1.1, alive, nav)
	_check(state.vertices.is_empty() and state.grammar.pending_count() == 0 and not results[-1]["ok"], "queued impact expiry clears immediately, even before earlier flight returns")
	results = state.resolve_shot(first, true, A, alive, nav)
	_check(state.vertices.is_empty() and results.is_empty(), "earlier flight cannot revive construction after queued anchor expiry")

func _mobile() -> void:
	var nav := _nav([Rect2(500, 200, 50, 50)])
	var alive: Dictionary[int, Vector2] = {11: A}
	var state := GeometerConstructionState.new()
	state.add_vertex(&"fire", A, 11, 0, nav)
	state.add_vertex(&"ice", B, 0, 0, nav)
	alive[11] = Vector2(120, 140)
	state.advance(1.0, alive, nav)
	_check(state.vertices[0].position == alive[11] and state.has_active_figure(), "dynamic anchor follows carrier alongside static anchor")
	var last_ground := alive[11]
	alive[11] = Vector2(520, 220)
	state.advance(1.0, alive, nav)
	_check(state.suspended and not state.has_active_figure() and state.figure_remaining == 4.0, "blocked moving anchor suspends without stopping clock")
	_check(state.consume_collapse().is_empty(), "suspended field cannot collapse")
	alive.erase(11)
	state.refresh(alive, nav)
	_check(state.vertices[0].actor_id == 0 and state.vertices[0].position == last_ground and state.vertices[0].remaining == 6.0, "death deposits at last valid ground without renewal")
	_check(state.has_active_figure() and state.figure_remaining == 4.0, "valid deposited wall resumes same lifetime")
	state.clear()
	alive[11] = A
	state.add_vertex(&"fire", A, 11, 0, nav)
	state.add_vertex(&"ice", B, 0, 0, nav)
	alive[11] = Vector2(950, 700)
	state.advance(6.0, alive, nav)
	_check(state.vertices.is_empty(), "invalid mobile geometry still expires")
	state.add_vertex(&"fire", A, 11, 0, nav)
	state.grammar.select_element(&"ice")
	var shot := state.reserve_shot(B, 0, false, 0, nav)
	alive[11] = Vector2(950, 700)
	var results := state.resolve_shot(shot, true, B, alive, nav)
	_check(not results[0]["ok"] and state.vertices.size() == 1 and state.vertices[0].position == alive[11], "impact validates against current carrier position, not stale geometry")
	state.clear()
	alive.clear()
	var first := state.reserve_shot(A, 0, false, 0, nav)
	state.grammar.select_element(&"ice")
	var second := state.reserve_shot(B, 11, false, 0, nav)
	state.resolve_shot(second, true, B, alive, nav)
	state.resolve_shot(first, true, A, alive, nav)
	_check(state.vertices.size() == 2 and state.vertices[1].actor_id == 0 and state.vertices[1].position == B, "confirmed impact queued before carrier death deposits, never binds corpse")
	state.clear()
	first = state.reserve_shot(A, 11, false, 0, nav)
	results = state.resolve_shot(first, false, A, alive, nav)
	_check(not results[0]["ok"] and state.vertices.is_empty(), "invalid target before impact adds no anchor")
	alive[11] = C
	state.add_vertex(&"fire", A, 0, 0, nav)
	state.add_vertex(&"ice", B, 0, 0, nav)
	state.add_vertex(&"fire", C, 11, 3, nav)
	var identity := state.construction_id
	alive[11] = Vector2(250, 100)
	state.advance(1.0, alive, nav)
	_check(state.suspended and state.shape == GeometerConstructionState.Shape.TRIANGLE and state.figure_remaining == 5.0, "degenerate mobile triangle suspends while retaining recipe")
	alive[11] = C
	state.advance(1.0, alive, nav)
	_check(state.has_active_figure() and state.construction_id == identity and state.figure_remaining == 4.0, "triangle resumes with no new identity or time")
	var edited := state.edit(Vector2(120, 420), 11, false, 3, nav)
	_check(edited["ok"] and not edited["formation"] and state.figure_remaining == 4.0, "resumed triangle edit cannot repeat closure resolution")
	var anchor_copy := state.vertices[2].snapshot()
	anchor_copy.position = Vector2.ZERO
	_check(state.vertices[2].position == Vector2(120, 420), "anchor snapshot is isolated from live state")
